### ISSUE TITLE
Use reverse domain name convention for package names and groupId

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/open-liberty-tools-intellij#2]
Use reverse domain name for [package names](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) and [groupId](https://maven.apache.org/guides/mini/guide-naming-conventions.html)

e.g.
- in build.gradle, use `io.openliberty` or `io.openliberty.tools` as the groupId
- use `io.openliberty.intellij` or `io.openliberty.tools.intellij` as the package name for Java code instead of `org.liberty.intellij`

**Comment by kathrynkodama** [comment]
Fixed with #3
