### ISSUE TITLE
Improve messages for confirmation dialogs

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/open-liberty-tools-intellij#24]
Consider more natural language for the confirmation messages.

e.g. "Start Liberty for XYZ project" instead of "Run Liberty Dev Start ..."

**Comment by kathrynkodama** [comment]
With the phrasing `Start Liberty for ...` will it be misinterpreted that the command will be `mvn liberty:start` as opposed to `mvn liberty:dev `?

**Comment by yeekangc** [comment]
I don't think so particularly in the context of a development tool/IDE.  I would think in such an environment, the default is to launch into dev mode.

If liberty:start is needed, that can be a future option to be added?
