### ISSUE TITLE
I followed the steps and watched the video without success

### ISSUE THREAD

**Issue by dbnex14** [OpenLiberty/open-liberty-tools-intellij#49]
the quality information to set up open Libety server with INtelliJ simply does not exist, at least I havent found it after long hours of googling.  I watched your 5:20 min video (https://www.youtube.com/watch?v=GIIhtdXwJ9A) and that did not help either.  I followed the steps at https://openliberty.io/blog/2020/09/03/open-liberty-tools-intellij.html with same result.

I am on MacOS Big Sur, using IntelliJ Ultimate 2021

1. First, intalling the liberty-maven-plugin 3.3.4 plugin did not add plugin to my project pom.xml.
2. Second even after adding it, I was getting the very same error 
`[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.3.4:dev (default-cli) on project springboot-backend: CWWKM2173E: Failed to install application from project io.learning:springboot-backend:jar:0.0.1-SNAPSHOT. The project packaging type is not supported. -> [Help 1]`
3. Finally, I see nowhere even mentioning **how  and where** is server.xml file that needs to be updated

**Comment by ericglau** [comment]
@dbnex14 Spring Boot applications are currently not generally supported with Liberty dev mode. Support for that will be addressed in https://github.com/OpenLiberty/ci.maven/issues/1144

For an example of how to run Spring Boot apps with Open Liberty (e.g. pom.xml setup and server.xml example), see the following guide: https://openliberty.io/guides/spring-boot.html 

If you have further questions and would like to discuss, feel free to post on the Gitter chatroom at https://gitter.im/OpenLiberty/developer-experience

**Comment by kathrynkodama** [comment]
Thank you for the feedback @dbnex14. 

This plugin is still an early tech preview release, we are working on developing and improving it. We will queue up issues to improve the documentation around how to configure your project with the Liberty Maven plugin, where to find the server.xml, which project types are supported, etc.

**Comment by yeekangc** [comment]
Yes, thank you for your feedback, @dbnex14.  We will look to provide additional guidance as Kathryn indicated.

**Comment by kathrynkodama** [comment]
Closing this issue as we have now added the [Getting Started](https://github.com/OpenLiberty/open-liberty-tools-intellij/blob/main/docs/GettingStarted.md) documentation to help users configure their projects with the Liberty Maven or Liberty Gradle plugins and use the features of Open Liberty Tools for IntelliJ.

 @dbnex14 If you have any other feedback for us, please open new issues. Thank you
